### PR TITLE
Added WhenFileSystemRenamed

### PR DESCRIPTION
**Pull request by StefanoP73**
All changes to add rename events to Topshelf.FileSystemWatcher

---
This change is [Reviewable](https://reviewable.io/reviews/tynor88/topshelf.simpleinjector/19)

### CODE REVIEW

**Comment by tynor88** [comment]
Hi, 

Thanks for the PR, i'll have a look at it this week!

**Comment by StefanoP73** [comment]
Sorry,
I'm new to Git and I don't know how to create a new pull request for my latest changes for Duplicated Events, I missed a Nuget package for System.Reactive.Ling and than I checked in all the updated projects :(

But I think this is a good addition to the project if you like it :D
In the Topshelf.FileSystemWatcher.Sample I added code for use of the new properties

**Comment by tynor88** [comment]
Reviewed 4 of 5 files at r1, 44 of 44 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19#-KcE-nV1mSsWQxVx3mOO:-KcE-nV1mSsWQxVx3mOP:bnpgpcv) (no related file):*
I added some comments, can you look through them.

---

*[Samples/Topshelf.FileSystemWatcher.Sample/Program.cs, line 36 at r2](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19#-KcE-aVlHJtmJsWZR_Gc:-KcE-aVlHJtmJsWZR_Gd:b-gle0uq) ([raw file](https://github.com/tynor88/topshelf.simpleinjector/blob/4ea32b9e0886d12cf7e8cab6d50f83ea85c9bae9/Samples/Topshelf.FileSystemWatcher.Sample/Program.cs#L36)):*
> ```Smalltalk
>         }
> 
>         private static void ConfigureDirectoryWorkCreated(FileSystemWatcherConfigurator obj)
> ```

Can this have a better variable name rather than obj?

---

*[Source/Topshelf.FileSystemWatcher/ServiceConfiguratorExtensions.cs, line 192 at r2](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19#-KcDzzkvsN8jXqZmH8pc:-KcDzzkvsN8jXqZmH8pd:bym8bih) ([raw file](https://github.com/tynor88/topshelf.simpleinjector/blob/4ea32b9e0886d12cf7e8cab6d50f83ea85c9bae9/Source/Topshelf.FileSystemWatcher/ServiceConfiguratorExtensions.cs#L192)):*
> ```Smalltalk
>                     //{
>                     //    watcher.EnableRaisingEvents = true;
>                     //}
> ```

Why is this not required anymore?

---

*[Tests/Topshelf.FileSystemWatcher.Test/TopshelfFileSystemWatcherTest.cs, line 17 at r2](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19#-KcE-Pwf_kNfSfjGtK4O:-KcE-Pwf_kNfSfjGtK4P:b-ovwawk) ([raw file](https://github.com/tynor88/topshelf.simpleinjector/blob/4ea32b9e0886d12cf7e8cab6d50f83ea85c9bae9/Tests/Topshelf.FileSystemWatcher.Test/TopshelfFileSystemWatcherTest.cs#L17)):*
> ```Smalltalk
>         public void TearDown()
>         {
>             if (Directory.Exists(TestContext.CurrentContext.WorkDirectory + _testDir))
> ```

Good idea!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19)*

**Comment by StefanoP73** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19#-KcE-nV1mSsWQxVx3mOO:-KcE97o3N_eZDf_iRJkv:b-q3483n) (no related file):*
<details><summary><i>Previously, tynor88 wrote…</i></summary><blockquote>

I added some comments, can you look through them.
</blockquote></details>

I hope understand the operation of this tools :-D
This week was full of news, before Github and than Reviewable!!!
Thank you

---

*[Samples/Topshelf.FileSystemWatcher.Sample/Program.cs, line 36 at r2](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19#-KcE-aVlHJtmJsWZR_Gc:-KcE40I8Me_Re5EJtzvC:b-i6p3ks) ([raw file](https://github.com/tynor88/topshelf.simpleinjector/blob/4ea32b9e0886d12cf7e8cab6d50f83ea85c9bae9/Samples/Topshelf.FileSystemWatcher.Sample/Program.cs#L36)):*
<details><summary><i>Previously, tynor88 wrote…</i></summary><blockquote>

Can this have a better variable name rather than obj?
</blockquote></details>

Yes, you are right! :+1: 
Something like fswConfig or extended name fileSystemWatcherConfigurator is a better name :-)

---

*[Source/Topshelf.FileSystemWatcher/ServiceConfiguratorExtensions.cs, line 192 at r2](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19#-KcDzzkvsN8jXqZmH8pc:-KcE5kOD4hW3f860a1_d:b90i77t) ([raw file](https://github.com/tynor88/topshelf.simpleinjector/blob/4ea32b9e0886d12cf7e8cab6d50f83ea85c9bae9/Source/Topshelf.FileSystemWatcher/ServiceConfiguratorExtensions.cs#L192)):*
<details><summary><i>Previously, tynor88 wrote…</i></summary><blockquote>

Why is this not required anymore?
</blockquote></details>

In the method CreateFileSystemWatcher the constructor use EnableRaisingEvents = true so all FileSystemWatcher created is already active

Also the code is in the "foreach (FileSystemWatcherConfigurator.DirectoryConfiguration config in configs)" so for each config the code create a FileSystemWatcher and add to the _watchers collection and than cycle it for activate.
This is a bad idea.

A better idea is to remove the EnableRaisingEvents = true from the constructor and move the commented code outside the cycle of configs

---

*[Tests/Topshelf.FileSystemWatcher.Test/TopshelfFileSystemWatcherTest.cs, line 17 at r2](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19#-KcE-Pwf_kNfSfjGtK4O:-KcE8xKLpRiVbrrVfCMV:b-y56ffb) ([raw file](https://github.com/tynor88/topshelf.simpleinjector/blob/4ea32b9e0886d12cf7e8cab6d50f83ea85c9bae9/Tests/Topshelf.FileSystemWatcher.Test/TopshelfFileSystemWatcherTest.cs#L17)):*
<details><summary><i>Previously, tynor88 wrote…</i></summary><blockquote>

Good idea!
</blockquote></details>

Thanks! :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19)*

**Comment by tynor88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Topshelf.FileSystemWatcher/ServiceConfiguratorExtensions.cs, line 192 at r2](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19#-KcDzzkvsN8jXqZmH8pc:-KcEVfB4n0zY_QLkHw5k:b-5a0hqd) ([raw file](https://github.com/tynor88/topshelf.simpleinjector/blob/4ea32b9e0886d12cf7e8cab6d50f83ea85c9bae9/Source/Topshelf.FileSystemWatcher/ServiceConfiguratorExtensions.cs#L192)):*
<details><summary><i>Previously, StefanoP73 wrote…</i></summary><blockquote>

In the method CreateFileSystemWatcher the constructor use EnableRaisingEvents = true so all FileSystemWatcher created is already active

Also the code is in the "foreach (FileSystemWatcherConfigurator.DirectoryConfiguration config in configs)" so for each config the code create a FileSystemWatcher and add to the _watchers collection and than cycle it for activate.
This is a bad idea.

A better idea is to remove the EnableRaisingEvents = true from the constructor and move the commented code outside the cycle of configs

</blockquote></details>

Yea, whatever you think is ok. Just delete the outcommented code. There is no need for it if the functionality is moved to a different place :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19)*

**Comment by StefanoP73** [comment]
Review status: 46 of 48 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Topshelf.FileSystemWatcher/ServiceConfiguratorExtensions.cs, line 192 at r2](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19#-KcDzzkvsN8jXqZmH8pc:-KcsLUi6IfH02CmSwPYa:bgauwif) ([raw file](https://github.com/tynor88/topshelf.simpleinjector/blob/4ea32b9e0886d12cf7e8cab6d50f83ea85c9bae9/Source/Topshelf.FileSystemWatcher/ServiceConfiguratorExtensions.cs#L192)):*
<details><summary><i>Previously, tynor88 wrote…</i></summary><blockquote>

Yea, whatever you think is ok. Just delete the outcommented code. There is no need for it if the functionality is moved to a different place :+1: 
</blockquote></details>

Sorry, I missed the replay to this comment.
Now the code is clean.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19)*

**Comment by tynor88** [comment]
Thanks, looks good. Merging

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Source/Topshelf.FileSystemWatcher/ServiceConfiguratorExtensions.cs, line 192 at r2](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19#-KcDzzkvsN8jXqZmH8pc:-KkzE9P1S5VM_Gc7j6To:bs7ao27) ([raw file](https://github.com/tynor88/topshelf.simpleinjector/blob/4ea32b9e0886d12cf7e8cab6d50f83ea85c9bae9/Source/Topshelf.FileSystemWatcher/ServiceConfiguratorExtensions.cs#L192)):*
<details><summary><i>Previously, StefanoP73 wrote…</i></summary><blockquote>

Sorry, I missed the replay to this comment.
Now the code is clean.
</blockquote></details>

Cool. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tynor88/topshelf.simpleinjector/19#-:-KkzE5ACkWVVOYgUDzqQ:b-kj0w7c)*

**Comment by tynor88** [comment]
merging in https://github.com/tynor88/Topshelf.SimpleInjector/pull/21

**Pull request closed without merging**
